# Generated by Django 4.0.3 on 2022-09-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='news_plan',
            field=models.CharField(blank=True, choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], default='D', max_length=2, null=True),
        ),
    ]
