# Generated by Django 4.0.3 on 2022-09-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='outro',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
