# Generated by Django 4.0.3 on 2022-11-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='twitter_handle',
            field=models.CharField(default='Username should start with @', max_length=50),
        ),
    ]
