# Generated by Django 4.0.3 on 2022-09-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_intro_alter_article_outro'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
