# Generated by Django 4.0.3 on 2022-09-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_section_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
