# Generated by Django 4.0.3 on 2022-09-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_thumb_alter_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='code_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
