# Generated by Django 4.0.9 on 2023-03-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='element_id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='link',
        ),
        migrations.RemoveField(
            model_name='section',
            name='list_items',
        ),
        migrations.RemoveField(
            model_name='section',
            name='name',
        ),
        migrations.AddField(
            model_name='section',
            name='section_name',
            field=models.CharField(default='Section n', max_length=50),
        ),
        migrations.AddField(
            model_name='section',
            name='section_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='outro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=512),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(default='Article summary'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumb_description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='heading',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.DeleteModel(
            name='ListItem',
        ),
    ]
