# Generated by Django 4.0.3 on 2022-09-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_section_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='section',
            name='text',
        ),
    ]
