# Generated by Django 4.0.3 on 2022-10-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='element_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
